### ISSUE TITLE
Can not activate the PRO plugin version

### ISSUE THREAD

**Issue by olegabr** [Freemius/wordpress-sdk#365]
**Actual Behavior**:
 -  `What is the issue? (*)` I can not activate the PRO plugin version.
 -  `What is the expected behavior?` I have configured my new plugin with freemius, integrated the SDK, deployed zip and marked it as release.
I have downloaded and installed free plugin version, then downloaded premium.
I've also created a PRO Licence key in admin panel and saved it in the Account page on my test wordpress site.

1. The message were shown with PLAN_TITLE placeholder instead the `Professional` name set in admin panel.
1. The premium version failed to activate because function names conflict with the free version. The function name is from my plugin.
1. I've deactivated the Free plugin to workaround the previos issue answered the question of why I'm doing it :-)
1. I've activated the downloaded PRO version and it says me that it is really PRO, but I see no PRO features. And in the Account page my plan is still shown as FREE.
1. The Change Plan button leads me to the payment page which is non-helpful because I'm already have the valid PRO license.
1. I've tried to press the Sync license button with result shown in the Stacktraces section

**Versions**: (*)
 -  `Freemius SDK Version:` 2.3.0
 -  `WordPress Version:` 5.2
 -  `PHP Version:` 7.0

**Plugin / Theme**: (*)
 -  `Name:` Cryptocurrency Product for WooCommerce
 -  `Slug:` cryptocurrency-product-for-woocommerce
 -  `Freemius ID:` 4418

**Additional Information**:
 -  `Browser Type: (*)` Chromium
 -  `Browser Version: (*)` Version 76.0.3809.100 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
 -  `OS: (*)` Ubuntu Linux kremlrus 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 -  `Stack Traces:` 

```
Fatal error: Uncaught Error: Call to a member function is_free() on boolean in /var/www/html/wp-content/plugins/cryptocurrency-product-for-woocommerce-premium/vendor/freemius/wordpress-sdk/includes/class-freemius.php:18901 Stack trace: #0 /var/www/html/wp-content/plugins/cryptocurrency-product-for-woocommerce-premium/vendor/freemius/wordpress-sdk/includes/class-freemius.php(18518): Freemius->_sync_plugin_license(false, true, false, NULL) #1 /var/www/html/wp-content/plugins/cryptocurrency-product-for-woocommerce-premium/vendor/freemius/wordpress-sdk/includes/class-freemius.php(20484): Freemius->_sync_license() #2 /var/www/html/wp-content/plugins/cryptocurrency-product-for-woocommerce-premium/vendor/freemius/wordpress-sdk/includes/class-freemius.php(20565): Freemius->_handle_account_edits() #3 /var/www/html/wp-includes/class-wp-hook.php(286): Freemius->_account_page_load('') #4 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #5 /var/www/html/wp-includes/plugin.php(465): WP_Hook->do_action in /var/www/html/wp-content/plugins/cryptocurrency-product-for-woocommerce-premium/vendor/freemius/wordpress-sdk/includes/class-freemius.php on line 18901

The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.
```

----
**Note:** `(*)` indicates required information. Without this information, your issue may be auto-closed.

> You can find your Freemius SDK version at `/freemius/start.php`

> You can find your Freemius product ID in the Freemius dashboard: `SETTINGS -> INTEGRATION`.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by olegabr** [comment]
resolved with support
