### ISSUE TITLE
Error message: Uncaught Error: Call to undefined method Freemius::ajax_url() 

### ISSUE THREAD

**Issue by princeahmed** [Freemius/wordpress-sdk#595]
Recently I have updated my plugin with the latest Freemius SDK - 2.5.2 and users are complaining about the below error

Error details
===================================
```
An E_ERROR error occurred on line 32 of the /home/admin/web/geek-speak.ru/public_html/wp-content/plugins/radio-player/freemius/templates/sticky-admin-notice-js.php file. Error message: Uncaught Error: Call to undefined method Freemius::ajax_url() in /home/admin/web/geek-speak.
ru/public_html/wp-content/plugins/radio-player/freemius/templates/sticky-admin-notice-js.php:32
Stack trace:
#0 /home/admin/web/geek-speak.ru/public_html/wp-content/plugins/radio-player/freemius/includes/fs-core-functions.php(50): require_once()
#1 /home/admin/web/geek-speak.ru/public_html/wp-content/plugins/radio-
player/freemius/includes/managers/class-fs-admin-notice-manager.php(195): fs_require_once_template()
#2 /home/admin/web/geek-speak.ru/public_html/wp-includes/class-wp-hook.php(308): FS_Admin_Notice_Manager::_add_sticky_dismiss_javascript()
#3 /home/admin/web/geek-speak.ru/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#4 /home/admin/web/geek-speak.ru/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /home/admin/web/geek-speak.ru/public_html/wp-admin/includes/template.php(2157): do_action()
#6 /home/admin/web/geek-speak.ru/public_html/wp-admin/update.php(53): iframe_foo
```

**Comment by vovafeldman** [comment]
Thanks for letting us know, @princeahmed. We are looking into it.

**Comment by princeahmed** [comment]
@vovafeldman 
I am going to release another update of my plugin.
Should I use the old version SDK - 2.4.5 with the new update of my plugin?

**Comment by vovafeldman** [comment]
@princeahmed, reverting to older SDK versions is not a good idea. Better to wait for a fix.

**Comment by fajardoleo** [comment]
@princeahmed We investigated the issue but didn't manage to reproduce it. Could you please contact us via [support AT freemius DOT com] with additional information on the issue so that we can investigate further?
