### ISSUE TITLE
Deprecations error with plugin_basename (str_replace & strpos)

### ISSUE THREAD

**Issue by rubas** [Freemius/wordpress-sdk#710]
# Problem

This function can return `null`, which gets picket up by `wp_normalize_path` and `wp_is_stream`.

https://github.com/Freemius/wordpress-sdk/blob/master/includes/supplements/fs-essential-functions-1.1.7.1.php#L42

# Stacktrace

```
ErrorException: Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated
#14 /wp/wp-includes/functions.php(2187): wp_normalize_path
#13 /wp/wp-includes/plugin.php(769): plugin_basename
#12 /app/mu-plugins/tablepress/libraries/freemius/start.php(181): require_once
#11 /app/mu-plugins/tablepress/tablepress.php(62): tb_tp_fs
#10 /app/mu-plugins/tablepress/tablepress.php(93): include_once
```

```
ErrorException: Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated
#15 /wp/wp-includes/functions.php(7288): wp_is_stream
#14 /wp/wp-includes/functions.php(2180): wp_normalize_path
#13 /wp/wp-includes/plugin.php(769): plugin_basename
#12 /app/mu-plugins/tablepress/libraries/freemius/start.php(181): require_once
#11 /app/mu-plugins/tablepress/tablepress.php(62): tb_tp_fs
#10 /app/mu-plugins/tablepress/tablepress.php(93): include_once
```

Reference: https://github.com/TablePress/TablePress/issues/196

**Comment by fajardoleo** [comment]
Hi @rubas, sorry for not getting to this earlier. Could you let us know if you're still encountering the same issue when using the latest version of TablePress (3.0.4) or our latest SDK version (2.11.0)?

**Comment by swashata** [comment]
Issue has been fixed https://github.com/Freemius/wordpress-sdk/releases/tag/2.12.0
