### ISSUE TITLE
Warning and error on first activation SDK V2.10.1

### ISSUE THREAD

**Issue by PeterSchulzNL** [Freemius/wordpress-sdk#778]
Hi there! 😄

After installing SDK V2.10.1 I'm getting the following warning and error:

Warning: require_once(/var/www/html/wp-content/plugins/code-manager-premium/freemius/templates/clone-resolution-js.php): Failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/code-manager-premium/freemius/includes/fs-core-functions.php on line 50 Fatal error: Uncaught Error: Failed opening required '/var/www/html/wp-content/plugins/code-manager-premium/freemius/templates/clone-resolution-js.php' (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/plugins/code-manager-premium/freemius/includes/fs-core-functions.php:50 Stack trace: #0 /var/www/html/wp-content/plugins/code-manager-premium/freemius/includes/managers/class-fs-clone-manager.php(816): fs_require_once_template('clone-resolutio...', Array) #1 /var/www/html/wp-includes/class-wp-hook.php(324): FS_Clone_Manager->_add_clone_resolution_javascript('') #2 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #3 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #4 /var/www/html/wp-admin/admin-footer.php(78): do_action('admin_footer', '') #5 /var/www/html/wp-admin/update.php(186): require_once('/var/www/html/w...') #6 {main} thrown in /var/www/html/wp-content/plugins/code-manager-premium/freemius/includes/fs-core-functions.php on line 50

This issue does not happen with my other plugin! (WP Data Access)

# 🐞 bug report

**Behavior**:
 -  `What is the issue? (*)`
  This only happens when activating the premium version. The reference to the old freemius directory still seems to be used during activation of the new version.  Once activated, the issue is gone. Installing the free version works without issues.
 -  `What is the expected behavior?`
 

**Versions**: (*)
 -  `Freemius SDK Version:`  2.10.1
 -  `WordPress Version:`  6.7.1
 -  `PHP Version:`  8.4

**Plugin / Theme**: (*)
 -  `Name:`  Code Manager
 -  `Slug:`  code-manager
 -  `Freemius ID:`  1.0.40 (not yet released)

**Additional Information**:
 -  `Browser Type: (*)` Chrome
 -  `Browser Version: (*)` Version 131.0.6778.109 (Official Build) (64-bit)
 -  `OS: (*)` Docker - Linux
 -  `Stack Traces:`

----
**Note:** `(*)` indicates required information. Without this information, your issue may be auto-closed.

> You can find your Freemius SDK version at `/freemius/start.php`

> You can find your Freemius product ID in the Freemius dashboard: `SETTINGS -> INTEGRATION`.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by PeterSchulzNL** [comment]
Fixed! It was a chacing issue.
